### ISSUE TITLE
Generated module requires ajv/lib/compile/equal

### ISSUE THREAD

**Issue by eagleflo** [epoberezkin/ajv-pack#19]
Hey there! Thank you for your work on ajv.

I was trying to generate a standalone validation module using `ajv-cli` version 3.0.0. (The schema I'm trying to compile should be simple enough to not hit any limitations mentioned in the README.)

```
$ ajv compile -s schema.json -o validation.js

schema schema.json is valid
```

The tool generates a module that begins with:

```
'use strict';
var equal = require('ajv/lib/compile/equal');
var validate = (function() {
  var refVal = [];
  return function validate(data, dataPath, parentData, parentDataProperty, rootData) {
[...]
```

Trying to import this module in Node (v12.2) results in the following error being thrown:

```
> var validation = require('./validation.js')
Thrown:
Error: Cannot find module 'ajv/lib/compile/equal'
```

I expected the generated module to be self-contained, with no external dependencies. Have I misunderstood something, or is this a bug?

**Comment by epoberezkin** [comment]
You still need to require ajv.

If you use webpack it will bundle equal in, it won't include the whole ajv.
